<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;


class Files extends Model
{
    //
    protected $table='files';
    protected $fillable = ['name', 'fileable_type', 'fileable_id'];


    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);
    }
    //backward
    public function fileable(){
        return $this->morphTo();
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::deleted(function ($item){

            $filePath = public_path('files/papers/').$item->name;
            if(file_exists($filePath)){
                @unlink($filePath);
            }

        });
    }


}
