<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;


class Thesis extends Model
{
    //
    protected $table = 'theses';

    protected $fillable = [
        'profile_id', 'degree_id', 'status', 'title', 'responsible',
        'group_aprovedate', 'council_aprovedate', 'code_date',
        'defense_date', 'score'
    ];

    // Forward
    public function checklists(){
        return $this->morphMany(Checklist::class, 'checkable');
    }
    // Backward
    public function profile(){
        return $this->belongsTo(Profile::class);
    }
    public function degree(){
        return $this->belongsTo(Degree::class);
    }
    public function getRouteKeyName()
    {
        return 'id'; // TODO: Change the autogenerated stub
    }

}
